### ISSUE TITLE
Unable to compile and install normally

### ISSUE THREAD

**Issue by ghost** [kryptokrona/hugin-native#5]
Compilation steps：

1.git clone https://github.com/kryptokrona/hugin-native.git.

2.git submodule update --init --recursive.

3.npm install.

![1](https://github.com/user-attachments/assets/39398184-7e15-4a0d-be6f-67684c8f460b)

4.npx install-expo-modules@latest.
![2](https://github.com/user-attachments/assets/041a26f9-e68f-4176-82c5-6540e5e0b4e2)
![3](https://github.com/user-attachments/assets/edabc524-7eb5-4b7b-b3c4-6c87c994d0f8)

**An error occurred during the fourth step of compilation and the compilation failed. Is it because a certain functional module is not included?**

My development environment is:
1. cmake version 3.30.3
2. macos Sequoia 15.0.1
3. Xcode 16.0

**Comment by n9lsjr** [comment]
Try deleting you node_modules folder, make sure you use `node 18.20.2` and try following the READme step by step again.

**Comment by ghost** [comment]
Use nvm to switch to 18.20.2, but the same error still occurs

1、cmake version 3.30.3
2、macos Sequoia 15.0.1
3、Xcode 16.0
4、node 18.20.2

**Comment by ghost** [comment]
it's ok :
`npx install-expo-modules@latest.`

`npm run ios`:

error Failed to build iOS project. "xcodebuild" exited with error code '65'. To debug build logs further, consider building your app with Xcode.app, by opening 'Hugin.xcworkspace'.
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -workspace Hugin.xcworkspace -configuration Debug -scheme Hugin -destination id=F4075718-6032-40D7-B286-79185148AF92

run with xcode:

Build input files cannot be found: '/Users/Danny/Documents/Code/hugin-native/bare-libs/ios/iphonesimulator/libhello_bare.a', '/Users/Danny/Documents/Code/hugin-native/bare-libs/ios/iphonesimulator/libbare.a'. Did you forget to declare these files as outputs of any script phases or custom build rules which produce them?

it's shows lack of some files:
```
libhello_bare.a
libbare.a
```

**Comment by ghost** [comment]
Some font issues.
